CREATE TABLE PERSON (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
	STREET VARCHAR(100) NOT NULL,
	NUMBER VARCHAR(30) NOT NULL,
	CEP VARCHAR(30),
	CITY VARCHAR(30),
	NEIGHBORHOOD VARCHAR(30),
	STATE VARCHAR(30),
	COMPLEMENT VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
