CREATE TABLE POSTING (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(50) NOT NULL,
	EXPIRATION_DATE DATE NOT NULL,
	PAYMENT_DATE DATE,
	VALUE DECIMAL(10,2) NOT NULL,
	NOTE VARCHAR(100),
	TYPE VARCHAR(20) NOT NULL,
	CATEGORY_ID BIGINT(20) NOT NULL,
	PERSON_ID BIGINT(20) NOT NULL,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
